Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
 
  # add a private network between localhost & VM using ip
  config.vm.network "private_network", ip: "1192.168.10.10"

  # copy folder
  config.vm.synced_folder ".", "/home/newvagrant"
  
  # provisisioning
  config.vm.provision "shell", path: "environment/provision.sh"

end